-- AlterTable
ALTER TABLE `Shipment` ADD COLUMN `providerPayload` JSON NULL,
    ADD COLUMN `providerShipmentId` VARCHAR(191) NULL,
    MODIFY `status` ENUM('PENDING', 'RATE_SELECTED', 'CREATED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';

