-- AlterTable: extend OrderStatus enum (additive — only adds PACKING/SHIPPED/DELIVERED)
ALTER TABLE `Order` MODIFY `status` ENUM('PENDING', 'PROCESSING', 'DELIVERING', 'COMPLETED', 'CANCELLED', 'PACKING', 'SHIPPED', 'DELIVERED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `OrderEvent` MODIFY `status` ENUM('PENDING', 'PROCESSING', 'DELIVERING', 'COMPLETED', 'CANCELLED', 'PACKING', 'SHIPPED', 'DELIVERED') NOT NULL;
